version: '2.1'

services:

  kong-migration:
      image: kong:0.14.0-alpine
      restart: on-failure
      depends_on:
        kong-database:
          condition: service_healthy
      environment:
        - KONG_DATABASE=postgres
        - KONG_PG_HOST=kong-database
      command: kong migrations up
  